### ISSUE TITLE
checkout out bvg-topological-map !

### ISSUE THREAD

**Issue by derhuerst** [domsson/vbb-interactive#1]
I made this a while ago: https://github.com/derhuerst/bvg-topological-map

Maybe we can join forces and work on an interactive map!

You can also come to the [Open Knowledge Lab Berlin](http://codefor.de/berlin/), [we meet every Monday](http://www.meetup.com/de-DE/OK-Lab-Berlin/).

**Comment by domsson** [comment]
Hey, you've got mail! :)
